version: '3'

services:
  web:
    image: ayushduttsharma/woise
    hostname: web
    mem_limit: 128m

  nginx:
    image: ayushduttsharma/woise-nginx
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
      - "3000:80"
    links:
      - web
    mem_limit: 128m
