name: woise
on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master", "develop"] # Adjust according to your branching strategy

jobs:
  build:
    runs-on: ubuntu-latest
    env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          DAILY_TOKEN: ${{ secrets.DAILY_TOKEN }}
          ONE_DAY_SECONDS: ${{ secrets.ONE_DAY_SECONDS }}
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          EXECTION_TIMEOUT: ${{ secrets.EXECTION_TIMEOUT }}
          TIME_TO_LIVE: ${{ secrets.TIME_TO_LIVE }}
          RUNPOD_SERVERLESS_ID: ${{ secrets.RUNPOD_SERVERLESS_ID }}
          RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
          TOTAL_WORKERS: ${{ secrets.TOTAL_WORKERS }}
          MAX_VIDEO_TIME: ${{ secrets.MAX_VIDEO_TIME }}
          AWS_BUCKET_AREA: ${{ secrets.AWS_BUCKET_AREA }}
          AWS_BUCKET_SECRET_ACCESS_KEY: ${{ secrets.AWS_BUCKET_SECRET_ACCESS_KEY }}
          AWS_BUCKET_ACCESS_KEY_ID: ${{ secrets.AWS_BUCKET_ACCESS_KEY_ID }}
          AWS_BUCKET_ENDPOINT_URL: ${{ secrets.AWS_BUCKET_ENDPOINT_URL }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASS: ${{secrets.DOCKER_PASS}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: Build woise image
        run: docker build ./my-app --file ./my-app/Dockerfile --tag woise:latest

      - name: Push woise Docker
        run: docker push ${{secrets.DOCKER_USER}}/woise:latest

      - name: Build nginx Image
        run: docker build ./nginx --file ./nginx/Dockerfile --tag woise-nginx:latest

      - name: Push nginx Docker
        run: docker push ${{secrets.DOCKER_USER}}/woise-nginx:latest

       